# Generated by Django 6.0.7 on 2026-08-02 00:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('tarifas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paquete',
            fields=[
                ('id_paquete', models.BigAutoField(primary_key=True, serialize=False)),
                ('guia_fastbox', models.CharField(max_length=20, unique=True)),
                ('tracking_original', models.CharField(blank=True, max_length=60, null=True)),
                ('tienda_origen', models.CharField(max_length=80)),
                ('descripcion', models.CharField(max_length=180)),
                ('peso_libras', models.DecimalField(decimal_places=2, max_digits=10)),
                ('costo_estimado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estado', models.CharField(choices=[('PREALERTA', 'Prealerta registrada'), ('BODEGA', 'Recibido en bodega'), ('TRANSITO', 'En tránsito'), ('ECUADOR', 'Llegó a Ecuador'), ('ENTREGA', 'Listo para entrega'), ('ENTREGADO', 'Entregado')], default='PREALERTA', max_length=20)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paquetes', to='clientes.cliente')),
                ('tarifa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paquetes', to='tarifas.tarifa')),
            ],
            options={
                'verbose_name': 'Paquete',
                'verbose_name_plural': 'Paquetes',
                'db_table': 'paquete',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoEnvio',
            fields=[
                ('id_movimiento', models.BigAutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('PREALERTA', 'Prealerta registrada'), ('BODEGA', 'Recibido en bodega'), ('TRANSITO', 'En tránsito'), ('ECUADOR', 'Llegó a Ecuador'), ('ENTREGA', 'Listo para entrega'), ('ENTREGADO', 'Entregado')], max_length=20)),
                ('detalle', models.CharField(max_length=200)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('paquete', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='envios.paquete')),
            ],
            options={
                'verbose_name': 'Movimiento de envío',
                'verbose_name_plural': 'Movimientos de envío',
                'db_table': 'movimiento_envio',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
