# Generated by Django 6.0.7 on 2026-08-02 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id_bitacora', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.CharField(max_length=80)),
                ('accion', models.CharField(max_length=80)),
                ('descripcion', models.CharField(max_length=220)),
                ('modulo', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Bitácora',
                'verbose_name_plural': 'Bitácora',
                'db_table': 'bitacora',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
