# Generated by Django 6.0.7 on 2026-08-02 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarifa',
            fields=[
                ('id_tarifa', models.BigAutoField(primary_key=True, serialize=False)),
                ('categoria', models.CharField(choices=[('TECNOLOGIA', 'Tecnología'), ('ROPA', 'Ropa'), ('ACCESORIOS', 'Accesorios'), ('OTROS', 'Otros')], max_length=20, unique=True)),
                ('valor_por_libra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.CharField(blank=True, max_length=180, null=True)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tarifa',
                'verbose_name_plural': 'Tarifas',
                'db_table': 'tarifa',
                'ordering': ['categoria'],
            },
        ),
    ]
